/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AppVersionMerchantDto
 */
export interface AppVersionMerchantDto {
  /**
   *
   * @type {boolean}
   * @memberof AppVersionMerchantDto
   */
  forceUpgrade: boolean;
}

/**
 * Check if a given object implements the AppVersionMerchantDto interface.
 */
export function instanceOfAppVersionMerchantDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'forceUpgrade' in value;

  return isInstance;
}

export function AppVersionMerchantDtoFromJSON(json: any): AppVersionMerchantDto {
  return AppVersionMerchantDtoFromJSONTyped(json, false);
}

export function AppVersionMerchantDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppVersionMerchantDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    forceUpgrade: json['forceUpgrade'],
  };
}

export function AppVersionMerchantDtoToJSON(value?: AppVersionMerchantDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    forceUpgrade: value.forceUpgrade,
  };
}
