/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AppVersionMerchantInput
 */
export interface AppVersionMerchantInput {
  /**
   *
   * @type {string}
   * @memberof AppVersionMerchantInput
   */
  version: string;
}

/**
 * Check if a given object implements the AppVersionMerchantInput interface.
 */
export function instanceOfAppVersionMerchantInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'version' in value;

  return isInstance;
}

export function AppVersionMerchantInputFromJSON(json: any): AppVersionMerchantInput {
  return AppVersionMerchantInputFromJSONTyped(json, false);
}

export function AppVersionMerchantInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AppVersionMerchantInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    version: json['version'],
  };
}

export function AppVersionMerchantInputToJSON(value?: AppVersionMerchantInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    version: value.version,
  };
}
