/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CatalogItemsAvailabilityMerchantInput
 */
export interface CatalogItemsAvailabilityMerchantInput {
  /**
   *
   * @type {Array<string>}
   * @memberof CatalogItemsAvailabilityMerchantInput
   */
  itemIds: Array<string>;
  /**
   *
   * @type {string}
   * @memberof CatalogItemsAvailabilityMerchantInput
   */
  availability: CatalogItemsAvailabilityMerchantInputAvailabilityEnum;
}

/**
 * @export
 */
export const CatalogItemsAvailabilityMerchantInputAvailabilityEnum = {
  Available: 'AVAILABLE',
  Unavailable: 'UNAVAILABLE',
  UnavailableToday: 'UNAVAILABLE_TODAY',
} as const;
export type CatalogItemsAvailabilityMerchantInputAvailabilityEnum =
  (typeof CatalogItemsAvailabilityMerchantInputAvailabilityEnum)[keyof typeof CatalogItemsAvailabilityMerchantInputAvailabilityEnum];

/**
 * Check if a given object implements the CatalogItemsAvailabilityMerchantInput interface.
 */
export function instanceOfCatalogItemsAvailabilityMerchantInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'itemIds' in value;
  isInstance = isInstance && 'availability' in value;

  return isInstance;
}

export function CatalogItemsAvailabilityMerchantInputFromJSON(
  json: any,
): CatalogItemsAvailabilityMerchantInput {
  return CatalogItemsAvailabilityMerchantInputFromJSONTyped(json, false);
}

export function CatalogItemsAvailabilityMerchantInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CatalogItemsAvailabilityMerchantInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    itemIds: json['itemIds'],
    availability: json['availability'],
  };
}

export function CatalogItemsAvailabilityMerchantInputToJSON(
  value?: CatalogItemsAvailabilityMerchantInput | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    itemIds: value.itemIds,
    availability: value.availability,
  };
}
