/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ContentSectionDto
 */
export interface ContentSectionDto {
  /**
   *
   * @type {string}
   * @memberof ContentSectionDto
   */
  subtitle: string;
  /**
   *
   * @type {string}
   * @memberof ContentSectionDto
   */
  description: string;
}

/**
 * Check if a given object implements the ContentSectionDto interface.
 */
export function instanceOfContentSectionDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'subtitle' in value;
  isInstance = isInstance && 'description' in value;

  return isInstance;
}

export function ContentSectionDtoFromJSON(json: any): ContentSectionDto {
  return ContentSectionDtoFromJSONTyped(json, false);
}

export function ContentSectionDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ContentSectionDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    subtitle: json['subtitle'],
    description: json['description'],
  };
}

export function ContentSectionDtoToJSON(value?: ContentSectionDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    subtitle: value.subtitle,
    description: value.description,
  };
}
