/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DateTimeDto
 */
export interface DateTimeDto {
  /**
   *
   * @type {number}
   * @memberof DateTimeDto
   */
  year: number;
  /**
   *
   * @type {number}
   * @memberof DateTimeDto
   */
  month: number;
  /**
   *
   * @type {number}
   * @memberof DateTimeDto
   */
  day: number;
  /**
   *
   * @type {number}
   * @memberof DateTimeDto
   */
  hour: number;
  /**
   *
   * @type {number}
   * @memberof DateTimeDto
   */
  minute: number;
}

/**
 * Check if a given object implements the DateTimeDto interface.
 */
export function instanceOfDateTimeDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'year' in value;
  isInstance = isInstance && 'month' in value;
  isInstance = isInstance && 'day' in value;
  isInstance = isInstance && 'hour' in value;
  isInstance = isInstance && 'minute' in value;

  return isInstance;
}

export function DateTimeDtoFromJSON(json: any): DateTimeDto {
  return DateTimeDtoFromJSONTyped(json, false);
}

export function DateTimeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateTimeDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    year: json['year'],
    month: json['month'],
    day: json['day'],
    hour: json['hour'],
    minute: json['minute'],
  };
}

export function DateTimeDtoToJSON(value?: DateTimeDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    year: value.year,
    month: value.month,
    day: value.day,
    hour: value.hour,
    minute: value.minute,
  };
}
