/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DeviceExpoPushNotificationTokenCustomerInput
 */
export interface DeviceExpoPushNotificationTokenCustomerInput {
  /**
   *
   * @type {string}
   * @memberof DeviceExpoPushNotificationTokenCustomerInput
   */
  expoNotificationToken: string;
}

/**
 * Check if a given object implements the DeviceExpoPushNotificationTokenCustomerInput interface.
 */
export function instanceOfDeviceExpoPushNotificationTokenCustomerInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'expoNotificationToken' in value;

  return isInstance;
}

export function DeviceExpoPushNotificationTokenCustomerInputFromJSON(
  json: any,
): DeviceExpoPushNotificationTokenCustomerInput {
  return DeviceExpoPushNotificationTokenCustomerInputFromJSONTyped(json, false);
}

export function DeviceExpoPushNotificationTokenCustomerInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeviceExpoPushNotificationTokenCustomerInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    expoNotificationToken: json['expoNotificationToken'],
  };
}

export function DeviceExpoPushNotificationTokenCustomerInputToJSON(
  value?: DeviceExpoPushNotificationTokenCustomerInput | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    expoNotificationToken: value.expoNotificationToken,
  };
}
