/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EmailLoginMerchantInput
 */
export interface EmailLoginMerchantInput {
  /**
   *
   * @type {string}
   * @memberof EmailLoginMerchantInput
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof EmailLoginMerchantInput
   */
  password: string;
}

/**
 * Check if a given object implements the EmailLoginMerchantInput interface.
 */
export function instanceOfEmailLoginMerchantInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'email' in value;
  isInstance = isInstance && 'password' in value;

  return isInstance;
}

export function EmailLoginMerchantInputFromJSON(json: any): EmailLoginMerchantInput {
  return EmailLoginMerchantInputFromJSONTyped(json, false);
}

export function EmailLoginMerchantInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EmailLoginMerchantInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
    password: json['password'],
  };
}

export function EmailLoginMerchantInputToJSON(value?: EmailLoginMerchantInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
  };
}
