/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EmptyResultDto
 */
export interface EmptyResultDto {
  /**
   *
   * @type {boolean}
   * @memberof EmptyResultDto
   */
  ok: boolean;
}

/**
 * Check if a given object implements the EmptyResultDto interface.
 */
export function instanceOfEmptyResultDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'ok' in value;

  return isInstance;
}

export function EmptyResultDtoFromJSON(json: any): EmptyResultDto {
  return EmptyResultDtoFromJSONTyped(json, false);
}

export function EmptyResultDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EmptyResultDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ok: json['ok'],
  };
}

export function EmptyResultDtoToJSON(value?: EmptyResultDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ok: value.ok,
  };
}
