/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ForgotPasswordInput
 */
export interface ForgotPasswordInput {
  /**
   *
   * @type {string}
   * @memberof ForgotPasswordInput
   */
  email: string;
}

/**
 * Check if a given object implements the ForgotPasswordInput interface.
 */
export function instanceOfForgotPasswordInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'email' in value;

  return isInstance;
}

export function ForgotPasswordInputFromJSON(json: any): ForgotPasswordInput {
  return ForgotPasswordInputFromJSONTyped(json, false);
}

export function ForgotPasswordInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ForgotPasswordInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json['email'],
  };
}

export function ForgotPasswordInputToJSON(value?: ForgotPasswordInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
  };
}
