/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MerchantAvailabilityMerchantInput
 */
export interface MerchantAvailabilityMerchantInput {
  /**
   *
   * @type {string}
   * @memberof MerchantAvailabilityMerchantInput
   */
  availability: MerchantAvailabilityMerchantInputAvailabilityEnum;
}

/**
 * @export
 */
export const MerchantAvailabilityMerchantInputAvailabilityEnum = {
  Available: 'AVAILABLE',
  Unavailable: 'UNAVAILABLE',
  UnavailableToday: 'UNAVAILABLE_TODAY',
} as const;
export type MerchantAvailabilityMerchantInputAvailabilityEnum =
  (typeof MerchantAvailabilityMerchantInputAvailabilityEnum)[keyof typeof MerchantAvailabilityMerchantInputAvailabilityEnum];

/**
 * Check if a given object implements the MerchantAvailabilityMerchantInput interface.
 */
export function instanceOfMerchantAvailabilityMerchantInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'availability' in value;

  return isInstance;
}

export function MerchantAvailabilityMerchantInputFromJSON(
  json: any,
): MerchantAvailabilityMerchantInput {
  return MerchantAvailabilityMerchantInputFromJSONTyped(json, false);
}

export function MerchantAvailabilityMerchantInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MerchantAvailabilityMerchantInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    availability: json['availability'],
  };
}

export function MerchantAvailabilityMerchantInputToJSON(
  value?: MerchantAvailabilityMerchantInput | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    availability: value.availability,
  };
}
