/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OrderDeliveryInfoMerchantDto
 */
export interface OrderDeliveryInfoMerchantDto {
  /**
   *
   * @type {string}
   * @memberof OrderDeliveryInfoMerchantDto
   */
  courierPhone?: string | null;
  /**
   *
   * @type {string}
   * @memberof OrderDeliveryInfoMerchantDto
   */
  courierName?: string | null;
  /**
   *
   * @type {string}
   * @memberof OrderDeliveryInfoMerchantDto
   */
  expectedPickupTime?: string | null;
  /**
   *
   * @type {string}
   * @memberof OrderDeliveryInfoMerchantDto
   */
  expectedDeliveryTime?: string | null;
  /**
   *
   * @type {string}
   * @memberof OrderDeliveryInfoMerchantDto
   */
  trackingUrl?: string | null;
  /**
   *
   * @type {string}
   * @memberof OrderDeliveryInfoMerchantDto
   */
  courierStatus: OrderDeliveryInfoMerchantDtoCourierStatusEnum;
}

/**
 * @export
 */
export const OrderDeliveryInfoMerchantDtoCourierStatusEnum = {
  Unassigned: 'UNASSIGNED',
  AssignedToCourier: 'ASSIGNED_TO_COURIER',
  AcceptedByCourier: 'ACCEPTED_BY_COURIER',
  CourierArrivedAtStore: 'COURIER_ARRIVED_AT_STORE',
  CourierPickedUpAtStore: 'COURIER_PICKED_UP_AT_STORE',
  CourierOnTheWay: 'COURIER_ON_THE_WAY',
  CourierArrivedAtCustomer: 'COURIER_ARRIVED_AT_CUSTOMER',
  DeliveredByCourier: 'DELIVERED_BY_COURIER',
  DeliveryFailed: 'DELIVERY_FAILED',
  CanceledByDriver: 'CANCELED_BY_DRIVER',
} as const;
export type OrderDeliveryInfoMerchantDtoCourierStatusEnum =
  (typeof OrderDeliveryInfoMerchantDtoCourierStatusEnum)[keyof typeof OrderDeliveryInfoMerchantDtoCourierStatusEnum];

/**
 * Check if a given object implements the OrderDeliveryInfoMerchantDto interface.
 */
export function instanceOfOrderDeliveryInfoMerchantDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'courierStatus' in value;

  return isInstance;
}

export function OrderDeliveryInfoMerchantDtoFromJSON(json: any): OrderDeliveryInfoMerchantDto {
  return OrderDeliveryInfoMerchantDtoFromJSONTyped(json, false);
}

export function OrderDeliveryInfoMerchantDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrderDeliveryInfoMerchantDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    courierPhone: !exists(json, 'courierPhone') ? undefined : json['courierPhone'],
    courierName: !exists(json, 'courierName') ? undefined : json['courierName'],
    expectedPickupTime: !exists(json, 'expectedPickupTime')
      ? undefined
      : json['expectedPickupTime'],
    expectedDeliveryTime: !exists(json, 'expectedDeliveryTime')
      ? undefined
      : json['expectedDeliveryTime'],
    trackingUrl: !exists(json, 'trackingUrl') ? undefined : json['trackingUrl'],
    courierStatus: json['courierStatus'],
  };
}

export function OrderDeliveryInfoMerchantDtoToJSON(
  value?: OrderDeliveryInfoMerchantDto | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    courierPhone: value.courierPhone,
    courierName: value.courierName,
    expectedPickupTime: value.expectedPickupTime,
    expectedDeliveryTime: value.expectedDeliveryTime,
    trackingUrl: value.trackingUrl,
    courierStatus: value.courierStatus,
  };
}
