/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OrderAddressMerchantDto
 */
export interface OrderAddressMerchantDto {
  /**
   *
   * @type {number}
   * @memberof OrderAddressMerchantDto
   */
  latitude: number;
  /**
   *
   * @type {number}
   * @memberof OrderAddressMerchantDto
   */
  longitude: number;
}

/**
 * Check if a given object implements the OrderAddressMerchantDto interface.
 */
export function instanceOfOrderAddressMerchantDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'latitude' in value;
  isInstance = isInstance && 'longitude' in value;

  return isInstance;
}

export function OrderAddressMerchantDtoFromJSON(json: any): OrderAddressMerchantDto {
  return OrderAddressMerchantDtoFromJSONTyped(json, false);
}

export function OrderAddressMerchantDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OrderAddressMerchantDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    latitude: json['latitude'],
    longitude: json['longitude'],
  };
}

export function OrderAddressMerchantDtoToJSON(value?: OrderAddressMerchantDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    latitude: value.latitude,
    longitude: value.longitude,
  };
}
