/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SetSquareLocationInput
 */
export interface SetSquareLocationInput {
  /**
   *
   * @type {string}
   * @memberof SetSquareLocationInput
   */
  locationId: string;
}

/**
 * Check if a given object implements the SetSquareLocationInput interface.
 */
export function instanceOfSetSquareLocationInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'locationId' in value;

  return isInstance;
}

export function SetSquareLocationInputFromJSON(json: any): SetSquareLocationInput {
  return SetSquareLocationInputFromJSONTyped(json, false);
}

export function SetSquareLocationInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SetSquareLocationInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    locationId: json['locationId'],
  };
}

export function SetSquareLocationInputToJSON(value?: SetSquareLocationInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    locationId: value.locationId,
  };
}
