/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SquareAuthCompleteDto
 */
export interface SquareAuthCompleteDto {
  /**
   *
   * @type {string}
   * @memberof SquareAuthCompleteDto
   */
  merchantId: string;
}

/**
 * Check if a given object implements the SquareAuthCompleteDto interface.
 */
export function instanceOfSquareAuthCompleteDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'merchantId' in value;

  return isInstance;
}

export function SquareAuthCompleteDtoFromJSON(json: any): SquareAuthCompleteDto {
  return SquareAuthCompleteDtoFromJSONTyped(json, false);
}

export function SquareAuthCompleteDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SquareAuthCompleteDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    merchantId: json['merchantId'],
  };
}

export function SquareAuthCompleteDtoToJSON(value?: SquareAuthCompleteDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    merchantId: value.merchantId,
  };
}
