/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SquareIntegrationStateDto
 */
export interface SquareIntegrationStateDto {
  /**
   *
   * @type {string}
   * @memberof SquareIntegrationStateDto
   */
  locationId: string;
  /**
   *
   * @type {string}
   * @memberof SquareIntegrationStateDto
   */
  locationName: string;
  /**
   *
   * @type {string}
   * @memberof SquareIntegrationStateDto
   */
  locationSimplifiedAddress: string;
}

/**
 * Check if a given object implements the SquareIntegrationStateDto interface.
 */
export function instanceOfSquareIntegrationStateDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'locationId' in value;
  isInstance = isInstance && 'locationName' in value;
  isInstance = isInstance && 'locationSimplifiedAddress' in value;

  return isInstance;
}

export function SquareIntegrationStateDtoFromJSON(json: any): SquareIntegrationStateDto {
  return SquareIntegrationStateDtoFromJSONTyped(json, false);
}

export function SquareIntegrationStateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SquareIntegrationStateDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    locationId: json['locationId'],
    locationName: json['locationName'],
    locationSimplifiedAddress: json['locationSimplifiedAddress'],
  };
}

export function SquareIntegrationStateDtoToJSON(value?: SquareIntegrationStateDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    locationId: value.locationId,
    locationName: value.locationName,
    locationSimplifiedAddress: value.locationSimplifiedAddress,
  };
}
