/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SquareLocation
 */
export interface SquareLocation {
  /**
   *
   * @type {string}
   * @memberof SquareLocation
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof SquareLocation
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof SquareLocation
   */
  simplifiedAddress: string;
}

/**
 * Check if a given object implements the SquareLocation interface.
 */
export function instanceOfSquareLocation(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'name' in value;
  isInstance = isInstance && 'simplifiedAddress' in value;

  return isInstance;
}

export function SquareLocationFromJSON(json: any): SquareLocation {
  return SquareLocationFromJSONTyped(json, false);
}

export function SquareLocationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SquareLocation {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    simplifiedAddress: json['simplifiedAddress'],
  };
}

export function SquareLocationToJSON(value?: SquareLocation | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    simplifiedAddress: value.simplifiedAddress,
  };
}
