/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SquareAuthStartDto
 */
export interface SquareAuthStartDto {
  /**
   *
   * @type {string}
   * @memberof SquareAuthStartDto
   */
  url: string;
}

/**
 * Check if a given object implements the SquareAuthStartDto interface.
 */
export function instanceOfSquareAuthStartDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'url' in value;

  return isInstance;
}

export function SquareAuthStartDtoFromJSON(json: any): SquareAuthStartDto {
  return SquareAuthStartDtoFromJSONTyped(json, false);
}

export function SquareAuthStartDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SquareAuthStartDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    url: json['url'],
  };
}

export function SquareAuthStartDtoToJSON(value?: SquareAuthStartDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    url: value.url,
  };
}
