/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SquareUnlinkInput
 */
export interface SquareUnlinkInput {
  /**
   *
   * @type {string}
   * @memberof SquareUnlinkInput
   */
  merchantId: string;
}

/**
 * Check if a given object implements the SquareUnlinkInput interface.
 */
export function instanceOfSquareUnlinkInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'merchantId' in value;

  return isInstance;
}

export function SquareUnlinkInputFromJSON(json: any): SquareUnlinkInput {
  return SquareUnlinkInputFromJSONTyped(json, false);
}

export function SquareUnlinkInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SquareUnlinkInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    merchantId: json['merchantId'],
  };
}

export function SquareUnlinkInputToJSON(value?: SquareUnlinkInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    merchantId: value.merchantId,
  };
}
