/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SquareLinkStateDto
 */
export interface SquareLinkStateDto {
  /**
   *
   * @type {string}
   * @memberof SquareLinkStateDto
   */
  state?: SquareLinkStateDtoStateEnum;
}

/**
 * @export
 */
export const SquareLinkStateDtoStateEnum = {
  Unlinked: 'UNLINKED',
  Pending: 'PENDING',
  Complete: 'COMPLETE',
  AttentionNeeded: 'ATTENTION_NEEDED',
} as const;
export type SquareLinkStateDtoStateEnum =
  (typeof SquareLinkStateDtoStateEnum)[keyof typeof SquareLinkStateDtoStateEnum];

/**
 * Check if a given object implements the SquareLinkStateDto interface.
 */
export function instanceOfSquareLinkStateDto(value: object): boolean {
  const isInstance = true;

  return isInstance;
}

export function SquareLinkStateDtoFromJSON(json: any): SquareLinkStateDto {
  return SquareLinkStateDtoFromJSONTyped(json, false);
}

export function SquareLinkStateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SquareLinkStateDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    state: !exists(json, 'state') ? undefined : json['state'],
  };
}

export function SquareLinkStateDtoToJSON(value?: SquareLinkStateDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    state: value.state,
  };
}
