/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SquareAuthCompleteInput
 */
export interface SquareAuthCompleteInput {
  /**
   *
   * @type {string}
   * @memberof SquareAuthCompleteInput
   */
  authorizationCode: string;
  /**
   *
   * @type {string}
   * @memberof SquareAuthCompleteInput
   */
  state: string;
}

/**
 * Check if a given object implements the SquareAuthCompleteInput interface.
 */
export function instanceOfSquareAuthCompleteInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'authorizationCode' in value;
  isInstance = isInstance && 'state' in value;

  return isInstance;
}

export function SquareAuthCompleteInputFromJSON(json: any): SquareAuthCompleteInput {
  return SquareAuthCompleteInputFromJSONTyped(json, false);
}

export function SquareAuthCompleteInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SquareAuthCompleteInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    authorizationCode: json['authorizationCode'],
    state: json['state'],
  };
}

export function SquareAuthCompleteInputToJSON(value?: SquareAuthCompleteInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    authorizationCode: value.authorizationCode,
    state: value.state,
  };
}
