/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SquareAuthStartInput
 */
export interface SquareAuthStartInput {
  /**
   *
   * @type {string}
   * @memberof SquareAuthStartInput
   */
  merchantId: string;
}

/**
 * Check if a given object implements the SquareAuthStartInput interface.
 */
export function instanceOfSquareAuthStartInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'merchantId' in value;

  return isInstance;
}

export function SquareAuthStartInputFromJSON(json: any): SquareAuthStartInput {
  return SquareAuthStartInputFromJSONTyped(json, false);
}

export function SquareAuthStartInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SquareAuthStartInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    merchantId: json['merchantId'],
  };
}

export function SquareAuthStartInputToJSON(value?: SquareAuthStartInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    merchantId: value.merchantId,
  };
}
