/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SquareLocation } from './SquareLocation';
import {
  SquareLocationFromJSON,
  SquareLocationFromJSONTyped,
  SquareLocationToJSON,
} from './SquareLocation';

/**
 *
 * @export
 * @interface SquareLocationsDto
 */
export interface SquareLocationsDto {
  /**
   *
   * @type {Array<SquareLocation>}
   * @memberof SquareLocationsDto
   */
  locations: Array<SquareLocation>;
}

/**
 * Check if a given object implements the SquareLocationsDto interface.
 */
export function instanceOfSquareLocationsDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'locations' in value;

  return isInstance;
}

export function SquareLocationsDtoFromJSON(json: any): SquareLocationsDto {
  return SquareLocationsDtoFromJSONTyped(json, false);
}

export function SquareLocationsDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SquareLocationsDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    locations: (json['locations'] as Array<any>).map(SquareLocationFromJSON),
  };
}

export function SquareLocationsDtoToJSON(value?: SquareLocationsDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    locations: (value.locations as Array<any>).map(SquareLocationToJSON),
  };
}
