/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TogglesDto
 */
export interface TogglesDto {
  /**
   *
   * @type {boolean}
   * @memberof TogglesDto
   */
  reducedServiceFee: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TogglesDto
   */
  supportChat: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TogglesDto
   */
  rewards: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TogglesDto
   */
  ethereumWallet: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TogglesDto
   */
  discounts: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TogglesDto
   */
  autoDeposits: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TogglesDto
   */
  easUpdates: boolean;
  /**
   *
   * @type {boolean}
   * @memberof TogglesDto
   */
  noshCourier: boolean;
}

/**
 * Check if a given object implements the TogglesDto interface.
 */
export function instanceOfTogglesDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'reducedServiceFee' in value;
  isInstance = isInstance && 'supportChat' in value;
  isInstance = isInstance && 'rewards' in value;
  isInstance = isInstance && 'ethereumWallet' in value;
  isInstance = isInstance && 'discounts' in value;
  isInstance = isInstance && 'autoDeposits' in value;
  isInstance = isInstance && 'easUpdates' in value;
  isInstance = isInstance && 'noshCourier' in value;

  return isInstance;
}

export function TogglesDtoFromJSON(json: any): TogglesDto {
  return TogglesDtoFromJSONTyped(json, false);
}

export function TogglesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TogglesDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    reducedServiceFee: json['reducedServiceFee'],
    supportChat: json['supportChat'],
    rewards: json['rewards'],
    ethereumWallet: json['ethereumWallet'],
    discounts: json['discounts'],
    autoDeposits: json['autoDeposits'],
    easUpdates: json['easUpdates'],
    noshCourier: json['noshCourier'],
  };
}

export function TogglesDtoToJSON(value?: TogglesDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    reducedServiceFee: value.reducedServiceFee,
    supportChat: value.supportChat,
    rewards: value.rewards,
    ethereumWallet: value.ethereumWallet,
    discounts: value.discounts,
    autoDeposits: value.autoDeposits,
    easUpdates: value.easUpdates,
    noshCourier: value.noshCourier,
  };
}
