/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserSessionMerchantDto
 */
export interface UserSessionMerchantDto {
  /**
   *
   * @type {string}
   * @memberof UserSessionMerchantDto
   */
  accessToken: string;
  /**
   *
   * @type {string}
   * @memberof UserSessionMerchantDto
   */
  tokenType: string;
  /**
   *
   * @type {number}
   * @memberof UserSessionMerchantDto
   */
  expiresIn: number;
}

/**
 * Check if a given object implements the UserSessionMerchantDto interface.
 */
export function instanceOfUserSessionMerchantDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'accessToken' in value;
  isInstance = isInstance && 'tokenType' in value;
  isInstance = isInstance && 'expiresIn' in value;

  return isInstance;
}

export function UserSessionMerchantDtoFromJSON(json: any): UserSessionMerchantDto {
  return UserSessionMerchantDtoFromJSONTyped(json, false);
}

export function UserSessionMerchantDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserSessionMerchantDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    accessToken: json['accessToken'],
    tokenType: json['tokenType'],
    expiresIn: json['expiresIn'],
  };
}

export function UserSessionMerchantDtoToJSON(value?: UserSessionMerchantDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    accessToken: value.accessToken,
    tokenType: value.tokenType,
    expiresIn: value.expiresIn,
  };
}
