/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserMerchantDto
 */
export interface UserMerchantDto {
  /**
   *
   * @type {string}
   * @memberof UserMerchantDto
   */
  id: string;
  /**
   *
   * @type {Array<string>}
   * @memberof UserMerchantDto
   */
  role: Array<UserMerchantDtoRoleEnum>;
  /**
   *
   * @type {string}
   * @memberof UserMerchantDto
   */
  email: string | null;
  /**
   *
   * @type {string}
   * @memberof UserMerchantDto
   */
  merchantManagerId: string | null;
  /**
   *
   * @type {string}
   * @memberof UserMerchantDto
   */
  merchantGroupAdminId: string | null;
}

/**
 * @export
 */
export const UserMerchantDtoRoleEnum = {
  Admin: 'ADMIN',
  Customer: 'CUSTOMER',
  MerchantLocationManager: 'MERCHANT_LOCATION_MANAGER',
  MerchantGroupAdmin: 'MERCHANT_GROUP_ADMIN',
} as const;
export type UserMerchantDtoRoleEnum =
  (typeof UserMerchantDtoRoleEnum)[keyof typeof UserMerchantDtoRoleEnum];

/**
 * Check if a given object implements the UserMerchantDto interface.
 */
export function instanceOfUserMerchantDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'role' in value;
  isInstance = isInstance && 'email' in value;
  isInstance = isInstance && 'merchantManagerId' in value;
  isInstance = isInstance && 'merchantGroupAdminId' in value;

  return isInstance;
}

export function UserMerchantDtoFromJSON(json: any): UserMerchantDto {
  return UserMerchantDtoFromJSONTyped(json, false);
}

export function UserMerchantDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserMerchantDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    role: json['role'],
    email: json['email'],
    merchantManagerId: json['merchantManagerId'],
    merchantGroupAdminId: json['merchantGroupAdminId'],
  };
}

export function UserMerchantDtoToJSON(value?: UserMerchantDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    role: value.role,
    email: value.email,
    merchantManagerId: value.merchantManagerId,
    merchantGroupAdminId: value.merchantGroupAdminId,
  };
}
