/* tslint:disable */
/* eslint-disable */
/**
 * NOSH-API
 * NOSH Backend API
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TogglesDto } from '../models/index';
import { TogglesDtoFromJSON, TogglesDtoToJSON } from '../models/index';
import * as runtime from '../runtime';

/**
 *
 */
export class TogglesApi extends runtime.BaseAPI {
  /**
   */
  async getAllRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TogglesDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/common/v1/toggles`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TogglesDtoFromJSON(jsonValue));
  }

  /**
   */
  async getAll(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TogglesDto> {
    const response = await this.getAllRaw(initOverrides);
    return await response.value();
  }
}
